name: tecaigo_native
description: TeCaiGO native Flutter app prototype.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand/tecaigo_logo.png
    - assets/photos/
    - assets/turismo/
    - assets/comercio/
    - assets/transporte/
